rule nifti2dicom:
    input:
        "data/{base_name}.nii.gz"
    output:
        directory("results/{base_name}")
    container:
        "resources/nifti2dicom.sif"
    shell:
        "nifti2dicom -i {input} -o {output} -y --studyinstanceuid {config[studyinstanceuid]} --patientname {config[patientname]}"

rule push_to_orthanc:
    input:
        "results/{base_name}/N2D_{num}.dcm"
    output:
        touch("results/{base_name}_{num}_pushed.done")
    shell:
        "curl -X POST {config[orthancurl]}/instances --data-binary @{input} -u {config[orthancusername]}:{config[orthancpassword]} -vf"
